### ISSUE TITLE
Some sort of Test Framework

### ISSUE THREAD

**Issue by astorm** [unirgy/convertm1m2#22]
It would be great is someone could set this project up with some sort of automated testing framwork for acceptance/integration tests.  Something that would let us quickly identify an issues like [this one](https://github.com/unirgy/convertm1m2/issues/21), quickly create a sample module fixture, and run these tests.

Right now there's a lot of mental inertia to testing changes with your own modules, since it means overwriting class files you've probably editing slightly to work around the limitations of the script (i.e. you don't want to overwrite your changes)

**Comment by astorm** [comment]
(opened this one with the hope of attracting someone to help on twitter)

**Comment by unirgy** [comment]
This is a very nice idea. Beyond testing for unparseable code, I'm not sure how much it is possible to automate testing arbitrary code.

The stage 2 should have caught this invalid code, did you try it?

**Comment by astorm** [comment]
Nope, I didn't try stage 2.  I'll keep that in mind text time.

**Comment by kschroeder** [comment]
Could you provide more information about what you are looking for in this testing framework?

**Comment by astorm** [comment]
@kschroeder I won't speak for @unirgy, but I'm looking for someone that would be able to look at this project, look at what is does, look at the sort of issues that are cropping up, and be able to come up with a test framework that would allow us to recreate specific issues and ensure there weren't regressions, as well as being able to create fixture modules, run the conversion on them, and then run tests after the files are created.

**Comment by kschroeder** [comment]
I don't know about the fixtures and conversion portion, but I am working on a project that streamlines Selenium testing by focusing on the activity instead of the commands, while also separating UI from that.  For the time being I'm focusing on getting M1 working.  I haven't gone deep into it but one use case is to allow people to build tests on M1, do their upgrade, and re-run them on M2.  Would that help with what you are looking at or something more integrated?

**Comment by steverobbins** [comment]
I'm not sure about testing a whole conversion, but you should be able to separate it into units (see what I did there), i.e.

Assert that contents of M1 file where changed from

```
class Acme_Module_Helper_Data
{
}
```

to

```
namespace Acme/Module/Helper;

class Data {
}
```

etc...

This will require breaking the project out of a single file, so that individual classes/functions can be loaded and tested without running the whole application.

**Comment by unirgy** [comment]
@steverobbins sounds reasonable. I'll split the class to separate file, make the methods public, and adjust file operations for mocking.

**Comment by astorm** [comment]
Just added a pull request for a bare bones PHPUnit test harness

https://github.com/unirgy/convertm1m2/pull/25

Thoughts?

**Comment by unirgy** [comment]
Please check the comments on the PR - closing this one meanwhile
