### ISSUE TITLE
Question: What's the Purpose of `_convertExtensionStage2`?

### ISSUE THREAD

**Issue by astorm** [unirgy/convertm1m2#8]
What's the job of the `_convertExtensionStage2` method? Short of explicitly passing in a stage parameter this method is never called.  This is a key part of the extension porting? Left over test code? Some sort of validation?  Or something else?

**Comment by unirgy** [comment]
This stage is run using either `http://127.0.0.1/convertm1m2/ConvertM1M2.php?a=2` or `$ php ConvertM1M2.php a=2`

What it does is - find all PHP files in extension output dir (mage2) and try to include them. PHP engine parses the files and throws fatal errors if any classes are invalid for parsing (invalid syntax, duplicate classes, missing parent classes, etc.) 

In the beginning of the script this was used to find errors during parsing/generating code. Now it's useful mostly for finding instances of unknown class mappings. 

Since fatal errors are unrecoverable, the errors will have to be fixed one by one after each run of stage 2.

**Comment by astorm** [comment]
Thanks!
